# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install -r requirements.txt
    pip install pytest sqlalchemy==2.0.12
  displayName: 'Deploy Notebooks to Databricks'

- task: databricksDeployScripts@0
  inputs:
    authMethod: 'bearer'
    region: 'westeurope'
    databricksPath: '/Shared'
    localPath: '/Users/Peizhi/Desktop/Main/DE/data-engineer/food-etl-RESTful'
    patToken: '$(DATABRICKS_PAT)'
  displayName: 'Deploy Notebooks to Databricks'
